update README and documentation

diff --git a/acctusage b/acctusage
--- a/acctusage
+++ b/acctusage
@@ -2,53 +2,51 @@
 
 # acctusage
 
-set -eu -o pipefail
+set -euo pipefail
 
 help() {
     # Display help information
-    printf "%s\n" "acctusage / Report Slurm account usage by users or accounts"
-    printf "%s\n" ""
-    printf "%s\n" "Usage: acctusage [-h] [-u <users>] [-a <accounts>] [-s <startdate>] [-e <enddate>]"
-    printf "%s\n" ""
-    printf "%s\n" "Options:"
-    printf "%s\n" ""
-    printf "%s\n" "-h  Display help"
-    printf "%s\n" ""
-    printf "%s\n" "-u  Specify users"
-    printf "%s\n" ""
-    printf "%s\n" "    * When only using users option, default value is current user"
-    printf "%s\n" "    * When only using accounts option, default value is all users in accounts"
-    printf "%s\n" "    * Multiple users can be specified with comma separation"
-    printf "%s\n" ""
-    printf "%s\n" "-a  Specify project accounts"
-    printf "%s\n" ""
-    printf "%s\n" "    * When only using users option, default value is all accounts"
-    printf "%s\n" "    * When only using accounts option, default value is all users in accounts"
-    printf "%s\n" "    * Multiple accounts can be specified with comma separation"
-    printf "%s\n" ""
-    printf "%s\n" "-s  Specify start date/time"
-    printf "%s\n" ""
-    printf "%s\n" "    * Default value is 7 days ago"
-    printf "%s\n" ""
-    printf "%s\n" "-e  Specify end date/time"
-    printf "%s\n" ""
-    printf "%s\n" "    * Default value is current date"
-    printf "%s\n" ""
-    printf "%s\n" "Examples:"
-    printf "%s\n" ""
-    printf "%s\n" "  acctusage"
-    printf "%s\n" "  acctusage -h"
-    printf "%s\n" "  acctusage -s 2023-01-01"
-    printf "%s\n" "  acctusage -u ttrojan"
-    printf "%s\n" "  acctusage -u ttrojan -s 2023-01-01"
-    printf "%s\n" "  acctusage -u ttrojan -a ttrojan_123"
-    printf "%s\n" "  acctusage -a ttrojan_123"
-    printf "%s\n" "  acctusage -a ttrojan_123 -s 2023-01-01 -e 2023-01-31"
+    cat << EOF
+acctusage / Report Slurm account usage by users or accounts
+
+Usage: acctusage [-h] [-u <users>] [-a <accounts>] [-s <startdate>] [-e <enddate>]
+
+Options:
+
+-h  Display help
+
+-u  Specify users
+    * When only using users option, default value is current user
+    * When only using accounts option, default value is all users in accounts
+    * Multiple users can be specified with comma separation
+
+-a  Specify project accounts
+    * When only using users option, default value is all accounts
+    * When only using accounts option, default value is all users in accounts
+    * Multiple accounts can be specified with comma separation
+
+-s  Specify start date/time
+    * Default value is 7 days ago
+
+-e  Specify end date/time
+    * Default value is current date
+
+Examples:
+
+  acctusage
+  acctusage -h
+  acctusage -s 2023-01-01
+  acctusage -u ttrojan
+  acctusage -u ttrojan -s 2023-01-01
+  acctusage -u ttrojan -a ttrojan_123
+  acctusage -a ttrojan_123
+  acctusage -a ttrojan_123 -s 2023-01-01 -e 2023-01-31
+EOF
 }
 
 # Set default values for option arguments
-users=
-accounts=
+users=""
+accounts=""
 startdate=$(date --date="-7 day" +%Y-%m-%d)
 enddate=$(date +%Y-%m-%d)
 
@@ -62,57 +60,63 @@ while getopts ":hu:a:s:e:" option; do
       u) # select users
          users="$OPTARG"
          if [[ $users =~ ^- ]]; then
-             printf "%s\n" "Error: Invalid argument to option -u"
+             echo "Error: Invalid argument to option -u" >&2
              exit 1
          fi
          ;;
       a) # select accounts
          accounts="$OPTARG"
          if [[ $accounts =~ ^- ]]; then
-             printf "%s\n" "Error: Invalid argument to option -a"
+             echo "Error: Invalid argument to option -a" >&2
              exit 1
          fi
          ;;
       s) # select startdate
          startdate="$OPTARG"
          if [[ $startdate =~ ^- ]]; then
-             printf "%s\n" "Error: Invalid argument to option -s"
+             echo "Error: Invalid argument to option -s" >&2
              exit 1
          fi
          ;;
       e) # select enddate
          enddate="$OPTARG"
          if [[ $enddate =~ ^- ]]; then
-             printf "%s\n" "Error: Invalid argument to option -e"
+             echo "Error: Invalid argument to option -e" >&2
              exit 1
          fi
          ;;
       \?) # invalid argument
-         printf "%s\n" "Error: Invalid option -$OPTARG" >&2
+         echo "Error: Invalid option -$OPTARG" >&2
          exit 1
          ;;
     esac
 done
 
 # Set output format
-format=login,accounts,cluster,tresname,used
+format="login,accounts,cluster,tresname,used"
 
 # Set TRES to display
-tres=cpu,gres/gpu,mem,billing
+tres="cpu,gres/gpu,mem,billing"
 
-printf "%s\n" "--------------------------------------------------------------------"
-printf "%s\n" "Slurm account usage from $startdate to $enddate"
-printf "%s\n" "--------------------------------------------------------------------"
-printf "%s\n" "     User         Account   Cluster       Resource             Usage"
-printf "%s\n" "--------- --------------- --------- -------------- -----------------"
-if [[ $users = "" && $accounts = "" ]]; then
-    sreport cluster accountutilizationbyuser -n -a users=$USER start=$startdate end=$enddate format=$format --tres=$tres
-elif [[ $accounts = "" ]]; then
-    sreport cluster accountutilizationbyuser -n -a users=$users start=$startdate end=$enddate format=$format --tres=$tres
-elif [[ $users = "" ]]; then
-    sreport cluster userutilizationbyaccount -n -a accounts=$accounts start=$startdate end=$enddate format=$format --tres=$tres
+cat << EOF
+--------------------------------------------------------------------
+Slurm account usage from $startdate to $enddate
+--------------------------------------------------------------------
+     User         Account   Cluster       Resource             Usage
+--------- --------------- --------- -------------- -----------------
+EOF
+
+if [[ -z $users && -z $accounts ]]; then
+    sreport cluster accountutilizationbyuser -n -a "users=$USER" "start=$startdate" "end=$enddate" "format=$format" "--tres=$tres"
+elif [[ -z $accounts ]]; then
+    sreport cluster accountutilizationbyuser -n -a "users=$users" "start=$startdate" "end=$enddate" "format=$format" "--tres=$tres"
+elif [[ -z $users ]]; then
+    sreport cluster userutilizationbyaccount -n -a "accounts=$accounts" "start=$startdate" "end=$enddate" "format=$format" "--tres=$tres"
 else
-    sreport cluster userutilizationbyaccount -n -a users=$users accounts=$accounts start=$startdate end=$enddate format=$format --tres=$tres
+    sreport cluster userutilizationbyaccount -n -a "users=$users" "accounts=$accounts" "start=$startdate" "end=$enddate" "format=$format" "--tres=$tres"
 fi
-printf "%s\n" "--------------------------------------------------------------------"
-printf "%s\n" "*CPU/GPU usage in minutes"
+
+cat << EOF
+--------------------------------------------------------------------
+*CPU/GPU usage in minutes
+EOF
diff --git a/cqueue b/cqueue
--- a/cqueue
+++ b/cqueue
@@ -2,43 +2,37 @@
 
 # cqueue
 
-set -eu -o pipefail
+set -euo pipefail
 
 help() {
     # Display help information
-    printf "%s\n" "cqueue / Display job queue information"
-    printf "%s\n" ""
-    printf "%s\n" "Usage: cqueue [-h] [-p <partition>] [-u <username>]"
-    printf "%s\n" ""
-    printf "%s\n" "Options:"
-    printf "%s\n" ""
-    printf "%s\n" "-h  Display help"
-    printf "%s\n" ""
-    printf "%s\n" "-p  Filter partitions"
-    printf "%s\n" ""
-    printf "%s\n" "    * Default value shows all partitions"
-    printf "%s\n" "    * Multiple partitions can be specified with comma separation"
-    printf "%s\n" ""
-    printf "%s\n" "-u  Filter users"
-    printf "%s\n" ""
-    printf "%s\n" "    * Default value shows all users"
-    printf "%s\n" "    * Multiple users can be specified with comma separation"
-    printf "%s\n" ""
-    printf "%s\n" "Examples:"
-    printf "%s\n" ""
-    printf "%s\n" "  cqueue"
-    printf "%s\n" "  cqueue -h"
-    printf "%s\n" "  cqueue -p epyc-64"
-    printf "%s\n" "  cqueue -u user1"
-    printf "%s\n" "  cqueue -p main -u user1"
-    printf "%s\n" "  cqueue -p main,gpu -u user1,user2"
+    cat << EOF
+cqueue - Display job queue information
+
+Usage: cqueue [-h] [-p <partition>] [-u <username>]
+
+Options:
+  -h  Display help
+  -p  Filter partitions
+      * Default value shows all partitions
+      * Multiple partitions can be specified with comma separation
+  -u  Filter users
+      * Default value shows all users
+      * Multiple users can be specified with comma separation
+
+Examples:
+  cqueue
+  cqueue -h
+  cqueue -p epyc-64
+  cqueue -u user1
+  cqueue -p main -u user1
+  cqueue -p main,gpu -u user1,user2
+EOF
 }
 
 # Set default values for option arguments
-users=
-partitions=
-# There is no all value for squeue --user or --partition options, so leave blank
-# See if statement below
+users=""
+partitions=""
 
 # Set squeue format
 format="%12i %.10u %.12j %.10P %.8T %.11M %.20R"
@@ -53,42 +47,42 @@ while getopts ":hp:u:" option; do
       p) # select partitions
          partitions=$OPTARG
          if [[ $partitions =~ ^- ]]; then
-           printf "%s\n" "Error: Invalid argument to option -p"
+           echo "Error: Invalid argument to option -p" >&2
            exit 1
          fi
          ;;
       u) # select users
          users=$OPTARG
          if [[ $users =~ ^- ]]; then
-           printf "%s\n" "Error: Invalid argument to option -u"
+           echo "Error: Invalid argument to option -u" >&2
            exit 1
          fi
          ;;
       \?) # invalid argument
-         printf "%s\n" "Error: Invalid option -$OPTARG" >&2
+         echo "Error: Invalid option -$OPTARG" >&2
          exit 1
          ;;
    esac
 done
 
-printf "%s\n" "-----------------------------------------------------------------------------------------"
-printf "%s\n" "      Job ID       User     Job Name  Partition    State     Elapsed     Nodelist(Reason)"
-printf "%s\n" "------------ ---------- ------------ ---------- -------- ----------- --------------------"
+echo "-----------------------------------------------------------------------------------------"
+echo "      Job ID       User     Job Name  Partition    State     Elapsed     Nodelist(Reason)"
+echo "------------ ---------- ------------ ---------- -------- ----------- --------------------"
 
-if [[ $partitions = "" ]]; then
-    if [[ $users = "" ]]; then
+if [[ -z $partitions ]]; then
+    if [[ -z $users ]]; then
         # List all users and all partitions
         squeue -h -o "$format"
     else
         # List specified users and all partitions
-        squeue -h -o "$format" -u $users
+        squeue -h -o "$format" -u "$users"
     fi
 else
-    if [[ $users = "" ]]; then
+    if [[ -z $users ]]; then
         # List all users and specified partitions
-        squeue -h -o "$format" -p $partitions
+        squeue -h -o "$format" -p "$partitions"
     else
         # List specified users and specified partitions
-        squeue -h -o "$format" -u $users -p $partitions
+        squeue -h -o "$format" -u "$users" -p "$partitions"
     fi
 fi
diff --git a/jobhist b/jobhist
--- a/jobhist
+++ b/jobhist
@@ -3,83 +3,81 @@
 # jobhist
 
 # Display a compact history of user's jobs with basic job information
-# Default setting is to display job history for past 7 days
+# Default setting is to display job history for the past 7 days
 # Based on output from sacct
 
-set -e -o pipefail
+set -euo pipefail
 
 # ANSI color codes
-RED='\033[0;31m'; 
-BLUE='\033[0;34m'; B='\033[0;34m';
-GREEN='\033[0;32m'; G='\033[0;32m';
-YELLOW='\033[0;33m'; Y='\033[0;33m';
-PURPLE='\033[0;35m'; P='\033[0;35m'; 
-RESET='\033[0m'; R='\033[0m';
+RED='\033[0;31m'
+BLUE='\033[0;34m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+PURPLE='\033[0;35m'
+RESET='\033[0m'
 
-# set default
-
-DAYS=1
+# Set default values
+DAYS=7
 user=$USER
 
-#  Define options
-while (( "$#" )); do
-    case $1 in 
+# Define options
+while [[ $# -gt 0 ]]; do
+    case $1 in
         -h | --help)
-            printf "$G%s$R\t%s\n" "Usage: $(basename $0)" "[OPTIONS]"
-            printf "\t$G%s$R\n" "-h, --help"  
-            printf "\t$G%s\t$R%s\n" "-d, --days" "number of days to list jobs from" 
-            printf "\t$G%s\t$R%s\n" "-u, --user" "user whose jobs to list"
+            printf "%s\t%s\n" "Usage: $(basename "$0")" "[OPTIONS]"
+            printf "\t%s\n" "-h, --help"
+            printf "\t%s\t%s\n" "-d, --days" "number of days to list jobs from"
+            printf "\t%s\t%s\n" "-u, --user" "user whose jobs to list"
             exit 0
             ;;
         -d | --days)
-            if [[ $2 =~ ^[0-9]+$ && $2 -ge 1 ]]; then 
+            if [[ $2 =~ ^[0-9]+$ && $2 -ge 1 ]]; then
                 DAYS=$2
-                echo "thanks for Days $DAYS"
+                echo "Thanks for specifying $DAYS days"
             else
-                printf "${RED}%s$R%s\n" "ERROR: " "days must be a positive integer"
+                printf "${RED}%s%s\n" "ERROR: " "days must be a positive integer"
                 exit 1
             fi
-            shift; shift; 
+            shift 2
             ;;
         -u | --user)
-            if [[ $2 =~ [[:alpha:]] || $2 -lt 1 ]]; then
+            if [[ $2 =~ ^[[:alnum:]]+$ ]]; then
                 user=$2
             else
-                printf "${RED}%s$R%s\n" "ERROR: " "user must be a alphanumeric string"
+                printf "${RED}%s%s\n" "ERROR: " "user must be an alphanumeric string"
+                exit 1
             fi
-            shift; shift;
-            ;; 
+            shift 2
+            ;;
         -* | --*=) # unsupported flags
             echo -e "${RED}Error: Unsupported flag $1${RESET}" >&2
             # rerun the script with --help
-            $0 --help
+            "$0" --help
             exit 1
             ;;
         *) # preserve positional arguments
-            PARAMS="$PARAMS $1"
+            PARAMS+=("$1")
             shift
-            ;; 
+            ;;
     esac
 done
 
-
-if [[ -z $2 ]]; then
-    user=$USER
-else
-    user=$2
-    # Check if user exists
-    if [[ "$(id $user 2>&1)" = *"no such user"* ]]; then
-        printf "%s\n" "No such user: $user"
-        exit 1
-    fi
+# Check if user exists
+if ! id -u "$user" >/dev/null 2>&1; then
+    printf "%s\n" "No such user: $user"
+    exit 1
 fi
 
 # Set sacct format
-format=Start,jobid%13,jobname%12,partition,state,elapsed%11,nnodes%5,ncpus%4,reqmem%8,reqtres%-50
+format="Start,jobid%13,jobname%12,partition,state,elapsed%11,nnodes%5,ncpus%4,reqmem%8,reqtres%-50"
 
 printf "%s\n" "---------------------------------------------------------------------------------------------------------"
 printf "%s\n" "          Startdate        Job ID     Job Name  Partition      State     Elapsed Nodes CPUs   Memory GPUs"
 printf "%s\n" "------------------- ------------- ------------ ---------- ---------- ----------- ----- ---- -------- ----"
-sacct --noheader -X -o $format -u $user -S $(date --date="-$DAYS day" +%Y-%m-%d) |
-    # Extract number of GPUs requested
+
+# Calculate the start date
+start_date=$(date --date="-${DAYS} day" +%Y-%m-%d)
+
+# Run sacct command and extract number of GPUs requested
+sacct --noheader -X -o "$format" -u "$user" -S "$start_date" |
     sed -r 's/billing=.*gres\/gpu=([^,]*),.*/\1/; s/billing=.*/0/'
